version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  - "automated"
  commit-message:
    prefix: ci

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "automated"
  commit-message:
    prefix: chore

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "automated"
  commit-message:
    prefix: chore

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "automated"
  commit-message:
    prefix: chore
