source "https://rubygems.org"

gem 'octopress', '~> 3.0'
gem 'octopress-date-format', '~> 3.0.3'
gem 'stringex', '~> 2.5.2'
gem 'sass-globbing', '~> 1.1.1'
gem 'compass', '~> 1.0.3'
gem 'haml', '~> 4.0.7'
gem 'jekyll-sitemap', '~> 0.9.0'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'rdiscount', '~> 2.1.8'
gem 'pygments.rb', '~> 0.6.3'
gem 'listen', '~> 3.0.3'
gem 'aws-sdk-v1', '~> 1.66.0'
gem 'json', '~> 1.8.3'
